pipeline {
  agent {
      label "docker"
  }
  parameters {
    choice(name: 'DOCKER_ACC', choices: ['percona','perconalab'], description: 'Docker repo to use: percona or perconalab')
    string(name: 'PS_VERSION', defaultValue: '8.0.16-7', description: 'Full PS version')
    string(name: 'PS_REVISION', defaultValue: '613e312', description: 'Short git hash for release')
  }
  stages {
    stage('Run test') {
      steps {
          script {
            currentBuild.displayName = "#${BUILD_NUMBER}-${PS_VERSION}-${PS_REVISION}"
            currentBuild.description = "${DOCKER_ACC}"
          }
          sh '''
            sudo yum install -y python3 python3-pip
            rm -rf python-venv-ubuntu
            python3 -m venv python-venv-ubuntu
            rm -rf package-testing
            git clone https://github.com/Percona-QA/package-testing.git --depth 1
            cd package-testing/docker-image-tests/ps
            pip3 install --user -r requirements.txt
            ./run.sh
          '''
      } //end steps
    } //end Run test stage
  } //end stages
  post {
    always {
      junit 'package-testing/docker-image-tests/ps/report.xml'
    }
  }
} //end pipeline
