---
- name: Cleanup
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: remove psmdb42 deb packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-server-mongodb
          - percona-server-mongodb-server
          - percona-server-mongodb-mongos
          - percona-server-mongodb-shell
          - percona-server-mongodb-tools
          - percona-server-mongodb-dbg
      when: ansible_os_family == "Debian"

    - name: remove psmdb42 rpm packages
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - percona-server-mongodb
          - percona-server-mongodb-server
          - percona-server-mongodb-mongos
          - percona-server-mongodb-shell
          - percona-server-mongodb-tools
          - percona-server-mongodb-debuginfo
      when: ansible_os_family == "RedHat"

    - name: check if process is stopped after package removal
      command: /package-testing/check_running.sh mongodb stopped
