---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: ${PLATFORM}
    region: ${AWS_DEFAULT_REGION}
    image: ${IMAGE}
    vpc_subnet_id: ${SUBNET}
    instance_type: ${INSTANCE_TYPE}
    ssh_user: ${USER}
    root_device_name: ${ROOT_DEVICE_NAME}
    instance_tags:
      iit-billing-tag: jenkins-pg-worker
provisioner:
  name: ansible
  log: True
  playbooks:
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
  lint:
    name: ansible-lint
    enabled: False
instances:
  - name: psmdb42-install
verifier:
  name: testinfra
  directory: ../default/tests
  options:
    verbose: true
    s: true
    junitxml: report.xml
  lint:
    name: flake8
    enabled: False
scenario:
  name: default
  destroy_sequence:
    - destroy
  clenup_sequence:
    - cleanup
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
