---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nginx-test-container
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    verbose: true
    junitxml: report.xml
