---
# tasks file for psmdb42-upgrade
- name: include tasks for test env setup
  include_tasks: ../../../tasks/test_prep.yml

- name: copy certificate for keyring vault
  copy:
    src: "{{ vault_cert }}"
    dest: /package-testing/scripts/psmdb_encryption/test.cer

- name: create token file for vault
  copy:
    dest: "/package-testing/scripts/psmdb_encryption/mongodb-test-vault-token"
    content: |
      {{ vault_token }}

- name: include tasks for enabling test repo
  include_tasks: ../../../tasks/enable_psmdb42_testing_repo.yml
  when: lookup('env', 'install_repo') == "testing" or lookup('env', 'install_repo') == ""

- name: include tasks for enabling main repo
  include_tasks: ../../../tasks/enable_psmdb42_main_repo.yml
  when: lookup('env', 'install_repo') == "main"

- name: include tasks for enabling experimental repo
  include_tasks: ../../../tasks/enable_psmdb42_experimental_repo.yml
  when: lookup('env', 'install_repo') == "experimental"

- name: install PSMDB packages
  include_tasks: ../../../tasks/install_psmdb.yml

- name: start mongod with service
  command: service mongod start
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: start mongod with systemctl
  command: systemctl start mongod
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6
