---
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ps80-install
    box: ${PLATFORM}
    memory: 1024
provisioner:
  name: ansible
  playbooks:
    cleanup: cleanup.yml
    prepare: ../../../playbooks/prepare.yml
  lint:
    name: ansible-lint
    enabled: False
verifier:
  name: testinfra
  options:
    verbose: true
    s: true
    junitxml: report.xml
  lint:
    name: flake8
